# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kc.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(423, 357)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.lb_unidades_distancia = QtWidgets.QLabel(Dialog)
        self.lb_unidades_distancia.setObjectName("lb_unidades_distancia")
        self.gridLayout.addWidget(self.lb_unidades_distancia, 14, 1, 1, 1)
        self.cBox_2 = QtWidgets.QCheckBox(Dialog)
        self.cBox_2.setObjectName("cBox_2")
        self.gridLayout.addWidget(self.cBox_2, 16, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 20, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.lb_distancias = QtWidgets.QLabel(Dialog)
        self.lb_distancias.setObjectName("lb_distancias")
        self.gridLayout.addWidget(self.lb_distancias, 14, 0, 1, 1)
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 20, 1, 1, 1)
        self.cb_unidades_distancia = QtWidgets.QComboBox(Dialog)
        self.cb_unidades_distancia.setObjectName("cb_unidades_distancia")
        self.gridLayout.addWidget(self.cb_unidades_distancia, 15, 1, 1, 1)
        self.pb_guardar = QtWidgets.QPushButton(Dialog)
        self.pb_guardar.setObjectName("pb_guardar")
        self.gridLayout.addWidget(self.pb_guardar, 31, 1, 1, 1)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 13, 0, 1, 1)
        self.cBox_4 = QtWidgets.QCheckBox(Dialog)
        self.cBox_4.setObjectName("cBox_4")
        self.gridLayout.addWidget(self.cBox_4, 18, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 13, 1, 1, 1)
        self.lb_resultado = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_resultado.setFont(font)
        self.lb_resultado.setObjectName("lb_resultado")
        self.gridLayout.addWidget(self.lb_resultado, 31, 0, 1, 1)
        self.lb_intro = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_intro.setFont(font)
        self.lb_intro.setObjectName("lb_intro")
        self.gridLayout.addWidget(self.lb_intro, 0, 0, 1, 1)
        self.lb_formula = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lb_formula.setFont(font)
        self.lb_formula.setObjectName("lb_formula")
        self.gridLayout.addWidget(self.lb_formula, 3, 0, 1, 1)
        self.cBox_1 = QtWidgets.QCheckBox(Dialog)
        self.cBox_1.setObjectName("cBox_1")
        self.gridLayout.addWidget(self.cBox_1, 15, 0, 1, 1)
        self.cBox_3 = QtWidgets.QCheckBox(Dialog)
        self.cBox_3.setObjectName("cBox_3")
        self.gridLayout.addWidget(self.cBox_3, 17, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        self.pb_salir = QtWidgets.QPushButton(Dialog)
        self.pb_salir.setObjectName("pb_salir")
        self.gridLayout.addWidget(self.pb_salir, 32, 1, 1, 1)
        self.lb_tiempo = QtWidgets.QLabel(Dialog)
        self.lb_tiempo.setObjectName("lb_tiempo")
        self.gridLayout.addWidget(self.lb_tiempo, 8, 0, 1, 1)
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 5, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 5, 0, 1, 1)
        self.cb_unidades_tiempo = QtWidgets.QComboBox(Dialog)
        self.cb_unidades_tiempo.setObjectName("cb_unidades_tiempo")
        self.gridLayout.addWidget(self.cb_unidades_tiempo, 9, 1, 1, 1)
        self.le_tiempo = QtWidgets.QLineEdit(Dialog)
        self.le_tiempo.setObjectName("le_tiempo")
        self.gridLayout.addWidget(self.le_tiempo, 9, 0, 1, 1)
        self.lb_unidades_tiempo = QtWidgets.QLabel(Dialog)
        self.lb_unidades_tiempo.setObjectName("lb_unidades_tiempo")
        self.gridLayout.addWidget(self.lb_unidades_tiempo, 8, 1, 1, 1)
        self.pb_calcular = QtWidgets.QPushButton(Dialog)
        self.pb_calcular.setObjectName("pb_calcular")
        self.gridLayout.addWidget(self.pb_calcular, 21, 1, 1, 1)

        self.retranslateUi(Dialog)
        self.pb_salir.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Cálculo del coeficiente de difusión para carbonatación"))
        self.lb_unidades_distancia.setText(_translate("Dialog", "Seleccione unidades de distancia"))
        self.cBox_2.setText(_translate("Dialog", "Distancias cara 2"))
        self.lb_distancias.setText(_translate("Dialog", "Seleccione qué distancias utilizar (d)"))
        self.pb_guardar.setText(_translate("Dialog", "Guardar"))
        self.cBox_4.setText(_translate("Dialog", "Distancias cara 4"))
        self.lb_resultado.setText(_translate("Dialog", "Kc = "))
        self.lb_intro.setText(_translate("Dialog", "Coeficiente de difusión para carbonatación:"))
        self.lb_formula.setText(_translate("Dialog", "Kc = d/RAIZ(t)"))
        self.cBox_1.setText(_translate("Dialog", "Distancias cara 1"))
        self.cBox_3.setText(_translate("Dialog", "Distancias cara 3"))
        self.pb_salir.setText(_translate("Dialog", "Salir"))
        self.lb_tiempo.setText(_translate("Dialog", "Tiempo transcurrido (t)"))
        self.lb_unidades_tiempo.setText(_translate("Dialog", "Seleccione unidades de tiempo"))
        self.pb_calcular.setText(_translate("Dialog", "Calcular"))
