# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'distCarb3.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 519)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("distCarb.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        # self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        # self.graphicsView.setAutoFillBackground(False)
        # self.graphicsView.setObjectName("graphicsView")
        # self.gridLayout_3.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 6, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.rb_escala = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_escala.setEnabled(False)
        self.rb_escala.setObjectName("rb_escala")
        self.gridLayout.addWidget(self.rb_escala, 0, 0, 1, 1)
        self.cb_caras = QtWidgets.QComboBox(self.centralwidget)
        self.cb_caras.setEditable(False)
        self.cb_caras.setObjectName("cb_caras")
        self.gridLayout.addWidget(self.cb_caras, 7, 0, 1, 1)
        # self.tableView = QtWidgets.QTableView(self.centralwidget)
        # self.tableView.setObjectName("tableView")
        # self.gridLayout.addWidget(self.tableView, 8, 0, 1, 1)
        self.tabla = QtWidgets.QTableWidget(self.centralwidget)
        self.tabla.setEnabled(False)
        self.tabla.setObjectName("tabla")
        self.tabla.setColumnCount(0)
        self.tabla.setRowCount(0)
        self.gridLayout.addWidget(self.tabla, 8, 0, 1, 1)

        self.pb_OK = QtWidgets.QPushButton(self.centralwidget)
        self.pb_OK.setEnabled(False)
        self.pb_OK.setObjectName("pb_OK")
        self.gridLayout.addWidget(self.pb_OK, 3, 1, 1, 1)
        self.pb_borrar = QtWidgets.QPushButton(self.centralwidget)
        self.pb_borrar.setEnabled(False)
        self.pb_borrar.setObjectName("pb_borrar")
        self.gridLayout.addWidget(self.pb_borrar, 8, 1, 1, 1)
        self.rb_linea = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_linea.setEnabled(False)
        self.rb_linea.setObjectName("rb_linea")
        self.gridLayout.addWidget(self.rb_linea, 4, 0, 1, 1)
        self.pb_rehacerlinea = QtWidgets.QPushButton(self.centralwidget)
        self.pb_rehacerlinea.setEnabled(False)
        self.pb_rehacerlinea.setObjectName("pb_rehacerlinea")
        self.gridLayout.addWidget(self.pb_rehacerlinea, 4, 1, 1, 1)
        self.pb_rehacerescala = QtWidgets.QPushButton(self.centralwidget)
        self.pb_rehacerescala.setEnabled(False)
        self.pb_rehacerescala.setObjectName("pb_rehacerescala")
        self.gridLayout.addWidget(self.pb_rehacerescala, 0, 1, 1, 1)
        self.le_escala = QtWidgets.QLineEdit(self.centralwidget)
        self.le_escala.setEnabled(False)
        self.le_escala.setObjectName("le_escala")
        self.gridLayout.addWidget(self.le_escala, 3, 0, 1, 1)
        self.rb_puntos = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_puntos.setEnabled(False)
        self.rb_puntos.setObjectName("rb_puntos")
        self.gridLayout.addWidget(self.rb_puntos, 5, 0, 1, 2)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 6, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 1, 1, 1)
        self.pb_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.pb_calcular.setEnabled(False)
        self.pb_calcular.setObjectName("pb_calcular")
        self.gridLayout_2.addWidget(self.pb_calcular, 5, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 924, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuInformacion = QtWidgets.QMenu(self.menubar)
        self.menuInformacion.setObjectName("menuInformacion")
        self.menuEdici_n = QtWidgets.QMenu(self.menubar)
        self.menuEdici_n.setObjectName("menuEdici_n")
        self.menuEjecutar = QtWidgets.QMenu(self.menubar)
        self.menuEjecutar.setObjectName("menuEjecutar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir_imagen = QtWidgets.QAction(MainWindow)
        self.actionAbrir_imagen.setObjectName("actionAbrir_imagen")
        self.actionCrear_informe = QtWidgets.QAction(MainWindow)
        self.actionCrear_informe.setEnabled(False)
        self.actionCrear_informe.setObjectName("actionCrear_informe")
        self.actionImagen = QtWidgets.QAction(MainWindow)
        self.actionImagen.setObjectName("actionImagen")
        self.actionResultados = QtWidgets.QAction(MainWindow)
        self.actionResultados.setObjectName("actionResultados")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionAyuda = QtWidgets.QAction(MainWindow)
        self.actionAyuda.setObjectName("actionAyuda")
        self.actionSobre_el_programa = QtWidgets.QAction(MainWindow)
        self.actionSobre_el_programa.setObjectName("actionSobre_el_programa")
        self.actionGuardar_imagen = QtWidgets.QAction(MainWindow)
        self.actionGuardar_imagen.setEnabled(False)
        self.actionGuardar_imagen.setObjectName("actionGuardar_imagen")
        self.actionBorrar_escala = QtWidgets.QAction(MainWindow)
        self.actionBorrar_escala.setEnabled(False)
        self.actionBorrar_escala.setObjectName("actionBorrar_escala")
        self.actionBorrar_l_nea = QtWidgets.QAction(MainWindow)
        self.actionBorrar_l_nea.setEnabled(False)
        self.actionBorrar_l_nea.setObjectName("actionBorrar_l_nea")
        self.actionBorrar_puntos = QtWidgets.QAction(MainWindow)
        self.actionBorrar_puntos.setEnabled(False)
        self.actionBorrar_puntos.setObjectName("actionBorrar_puntos")
        self.actionPreferencias = QtWidgets.QAction(MainWindow)
        self.actionPreferencias.setEnabled(False)
        self.actionPreferencias.setObjectName("actionPreferencias")
        self.actionCalcular_coeficiente_difusi_n = QtWidgets.QAction(MainWindow)
        self.actionCalcular_coeficiente_difusi_n.setObjectName("actionCalcular_coeficiente_difusi_n")
        self.menuArchivo.addAction(self.actionAbrir_imagen)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionCrear_informe)
        self.menuArchivo.addAction(self.actionGuardar_imagen)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menuInformacion.addAction(self.actionAyuda)
        self.menuInformacion.addAction(self.actionSobre_el_programa)
        self.menuEdici_n.addAction(self.actionBorrar_escala)
        self.menuEdici_n.addAction(self.actionBorrar_l_nea)
        self.menuEdici_n.addAction(self.actionBorrar_puntos)
        self.menuEdici_n.addSeparator()
        self.menuEdici_n.addAction(self.actionPreferencias)
        self.menuEjecutar.addAction(self.actionCalcular_coeficiente_difusi_n)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuEdici_n.menuAction())
        self.menubar.addAction(self.menuEjecutar.menuAction())
        self.menubar.addAction(self.menuInformacion.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "distCarb (versión beta)"))
        self.rb_escala.setText(_translate("MainWindow", "Escala"))
        self.pb_OK.setText(_translate("MainWindow", "OK"))
        self.pb_borrar.setText(_translate("MainWindow", "Borrar punto"))
        self.rb_linea.setText(_translate("MainWindow", "Linea"))
        self.pb_rehacerlinea.setText(_translate("MainWindow", "Rehacer"))
        self.pb_rehacerescala.setText(_translate("MainWindow", "Rehacer"))
        self.rb_puntos.setText(_translate("MainWindow", "Puntos"))
        self.pb_calcular.setText(_translate("MainWindow", "Calcular"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuInformacion.setTitle(_translate("MainWindow", "Información"))
        self.menuEdici_n.setTitle(_translate("MainWindow", "Edición"))
        self.menuEjecutar.setTitle(_translate("MainWindow", "Ejecutar"))
        self.actionAbrir_imagen.setText(_translate("MainWindow", "Abrir imagen"))
        self.actionAbrir_imagen.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionCrear_informe.setText(_translate("MainWindow", "Crear informe"))
        self.actionCrear_informe.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionImagen.setText(_translate("MainWindow", "Imagen"))
        self.actionResultados.setText(_translate("MainWindow", "Resultados"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionSalir.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionAyuda.setText(_translate("MainWindow", "Ayuda"))
        self.actionAyuda.setShortcut(_translate("MainWindow", "F1"))
        self.actionSobre_el_programa.setText(_translate("MainWindow", "Sobre el programa"))
        self.actionGuardar_imagen.setText(_translate("MainWindow", "Guardar imagen"))
        self.actionGuardar_imagen.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.actionBorrar_escala.setText(_translate("MainWindow", "Borrar escala"))
        self.actionBorrar_l_nea.setText(_translate("MainWindow", "Borrar línea"))
        self.actionBorrar_puntos.setText(_translate("MainWindow", "Borrar puntos"))
        self.actionPreferencias.setText(_translate("MainWindow", "Preferencias"))
        self.actionPreferencias.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionCalcular_coeficiente_difusi_n.setText(_translate("MainWindow", "Calcular coef. Difusión"))


